version: "2"

run:
  timeout: 10m
  tests: true
  issues-exit-code: 1

issues:
  exclude-dirs:
    - vendor

linters:
  default: none  # v2 format - disable all linters by default
  enable:
    - govet      # Go vet checks
    - ineffassign # Detect ineffective assignments
    - unused     # Check for unused code