name: KloneKit CI/CD

#
# TRIGGERS
#
on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual triggering

#
# PERMISSIONS
#
permissions:
  contents: write # To create releases
  pages: write    # To deploy to GitHub Pages
  id-token: write # To authenticate with GitHub Pages

#
# JOBS
#
jobs:
  # ----------------------------------------------------------------
  # LINT: Ensure code quality and style consistency.
  # ----------------------------------------------------------------
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

  # ----------------------------------------------------------------
  # TEST: Run the full test suite.
  # ----------------------------------------------------------------
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Run tests with coverage
        run: make test

  # ----------------------------------------------------------------
  # BUILD: Compile binaries for all target platforms.
  # ----------------------------------------------------------------
  build:
    name: Build Binaries
    needs: [lint, test]
    # Only run builds on tags or manual dispatch, not on regular pushes
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            binary-ext: ""
            artifact-name: "linux-amd64"
          - goos: darwin
            goarch: amd64
            binary-ext: ""
            artifact-name: "darwin-amd64"
          - goos: darwin
            goarch: arm64
            binary-ext: ""
            artifact-name: "darwin-arm64"
          - goos: windows
            goarch: amd64
            binary-ext: ".exe"
            artifact-name: "windows-amd64"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Get version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="dev-$(date +%Y%m%d-%H%M%S)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          BINARY_NAME="klonekit-${{ steps.version.outputs.version }}-${{ matrix.artifact-name }}${{ matrix.binary-ext }}"
          go build -ldflags "-X main.version=${{ steps.version.outputs.version }}" -o "$BINARY_NAME" ./cmd/klonekit
          echo "Built: $BINARY_NAME"
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: klonekit-${{ steps.version.outputs.version }}-${{ matrix.artifact-name }}
          path: klonekit-${{ steps.version.outputs.version }}-${{ matrix.artifact-name }}${{ matrix.binary-ext }}

  # ----------------------------------------------------------------
  # DEPLOY-DOCS: Deploy the documentation to GitHub Pages.
  # ----------------------------------------------------------------
  deploy-docs:
    name: Deploy Documentation
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MkDocs dependencies
        run: |
          pip install -r user-docs/requirements.txt
      - name: Build documentation
        run: |
          cd user-docs
          mkdocs build --config-file mkdocs.yml
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./user-docs/site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  # ----------------------------------------------------------------
  # RELEASE: Create a GitHub Release when a tag is pushed.
  # ----------------------------------------------------------------
  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Download all binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/klonekit-${{ steps.version.outputs.version }}-linux-amd64/*
            binaries/klonekit-${{ steps.version.outputs.version }}-darwin-amd64/*
            binaries/klonekit-${{ steps.version.outputs.version }}-darwin-arm64/*
            binaries/klonekit-${{ steps.version.outputs.version }}-windows-amd64/*

  # ----------------------------------------------------------------
  # UPDATE-HOMEBREW: Update homebrew formula after successful release.
  # ----------------------------------------------------------------
  update-homebrew:
    name: Update Homebrew Formula
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_no_v=${VERSION#v}" >> $GITHUB_OUTPUT
      - name: Download release assets
        run: |
          VERSION=${{ steps.version.outputs.version }}
          VERSION_NO_V=${{ steps.version.outputs.version_no_v }}

          # Download binaries for SHA256 calculation
          curl -L -o klonekit-darwin-amd64 "https://github.com/salman-frs/klonekit/releases/download/${VERSION}/klonekit-${VERSION}-darwin-amd64"
          curl -L -o klonekit-darwin-arm64 "https://github.com/salman-frs/klonekit/releases/download/${VERSION}/klonekit-${VERSION}-darwin-arm64"
          curl -L -o klonekit-linux-amd64 "https://github.com/salman-frs/klonekit/releases/download/${VERSION}/klonekit-${VERSION}-linux-amd64"

          # Calculate SHA256 hashes
          SHA_DARWIN_AMD64=$(sha256sum klonekit-darwin-amd64 | cut -d' ' -f1)
          SHA_DARWIN_ARM64=$(sha256sum klonekit-darwin-arm64 | cut -d' ' -f1)
          SHA_LINUX_AMD64=$(sha256sum klonekit-linux-amd64 | cut -d' ' -f1)

          echo "sha_darwin_amd64=$SHA_DARWIN_AMD64" >> $GITHUB_ENV
          echo "sha_darwin_arm64=$SHA_DARWIN_ARM64" >> $GITHUB_ENV
          echo "sha_linux_amd64=$SHA_LINUX_AMD64" >> $GITHUB_ENV
      - name: Checkout homebrew tap repository
        uses: actions/checkout@v4
        with:
          repository: salman-frs/homebrew-klonekit
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap
      - name: Update formula
        run: |
          cd homebrew-tap
          VERSION_NO_V=${{ steps.version.outputs.version_no_v }}

          # Update klonekit.rb with new version and SHA256 hashes
          sed -i "s/version \".*\"/version \"$VERSION_NO_V\"/" klonekit.rb
          sed -i "s/PLACEHOLDER_SHA256_DARWIN_AMD64/${{ env.sha_darwin_amd64 }}/" klonekit.rb
          sed -i "s/PLACEHOLDER_SHA256_DARWIN_ARM64/${{ env.sha_darwin_arm64 }}/" klonekit.rb
          sed -i "s/PLACEHOLDER_SHA256_LINUX_AMD64/${{ env.sha_linux_amd64 }}/" klonekit.rb
      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add klonekit.rb
          git commit -m "Update klonekit to ${{ steps.version.outputs.version_no_v }}"
          git push
